#include <stdio.h>
#include <stdlib.h>

#include "comand.h"
#include "config.h"
#include "parser.h"

int main (void)
{
    FILE* file = fopen (ADDRESS_HASH, "w");
    if (file == NULL)
    {
        printf ("ERROR: NULL file in gen-hash\n");
        return 1;
    }

    fprintf (file,
             "// This file is autogenerated\n// Do not change it!!!\n\n");
    fprintf (file,
             "#ifndef HASH_CMD_H\n#define HASH_CMD_H\n\n");

    // fprintf (file,
    //          "enum HASH_COMANDS\n{\n");

    size_t amount_cmd = sizeof (CHAR_COMANDS) / sizeof (CHAR_COMANDS[0]);

    int* hash_massive = (int*) calloc (amount_cmd, sizeof (int));
    if (hash_massive == NULL)
    {
        printf ("ERROR: NULL calloc in gen-hash\n");
        fclose (file);
        return 1;
    }

    for (size_t i = 0; i < amount_cmd; i++)
    {
        int hash = make_hash (CHAR_COMANDS[i]);
        // fprintf (file,
        //          "    HASH_%s = %d,\n",
        //          CHAR_COMANDS[i],
        //          hash);
        hash_massive[i] = hash;
    }

    fprintf (file,
             "\n\n// This massive needed to simple checks hash code in cycle\n");
    fprintf (file,
             "int MASS_HASH[] =\n{\n");

    for (size_t i = 0; i < amount_cmd; i++)
    {
        fprintf(file,
                "    %d,\n",
                hash_massive[i]);
    }

    fprintf (file,
             "};\n\n#endif // HASH_CMD_H\n");

    fclose (file);
    free (hash_massive);

    return 0;
}
