// This file is autogenerated
// Do not change it!!!

#ifndef HASH_CMD_H
#define HASH_CMD_H



// This massive needed to simple checks hash code in cycle
int MASS_HASH[] =
{
    25711,
    25975,
};

#endif // HASH_CMD_H
